#!/bin/bash

#    Copyright 2015-2017 Gilbert Standen
#    This file is part of orabuntu-lxc: https://github.com/gstanden/orabuntu-lxc
#
#    Orabuntu-lxc is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Orabuntu-lxc is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with orabuntu-lxc.  If not, see <http://www.gnu.org/licenses/>.
#
#    v2.8 GLS 20151231
#    v3.0 GLS 20160710
#    v3.1 GLS 20160925
#    v4.0 GLS 20170906
#
#    !! SEE THE README FILE FOR COMPLETE INSTRUCTIONS FIRST BEFORE RUNNING !!
#
#    sudo ALL privilege is required 	prior to running!
#    internet connectivity is required 	prior to running!
#
#	0.	Run these scripts on Ubuntu as the Ubuntu admin install non-root (i.e. the user with 'sudo ALL' privilege);  On CentOS run the scripts as the 'root' user.
#	1.	This SCST Linux SAN for Orabuntu-LXC is installed using the create-scst.sh script which runs the other SCST scripts.
#	2.	The create-scst-oracle.sh script can be run with parameters which you can set in the create-scst.sh file (see below). 
#		Don't edit the create-scst-oracle.sh file because it is configued to work with create-scst-multipath.sh which follows as the next script to run.
#		You can change the SAN after all scripts have run by running 'scstadmin -clear_config -f' and then creating your own SAN specification.
#		By doing it this way you will get the auto-configuration of the multipath.conf and the 99-oracle.rules files which this software does for you automatically.
#	3.	If you don't set the parameters for the create-scst-oracle.sh script it is run with default parameters.
#		Those default parameters are as shown below:
#
#	User:     Run this program as root if on RedHat/CentOS/Oracle Linux or similar; Run this program as the install admin user (user with 'sudo' privilege) if on Ubuntu or similar.
#	Usage:    create-scst-oracle.sh com.yourdomain ScstGroupName AsmRedundancy Sysd1SizeGb Data1SizeGb Reco1SizeGb LogicalBlkSiz 
#	Example:  create-scst-oracle.sh com.orabuntu-lxc lxc1 external 10G 30G 30G
#
#	Note1:    If you do not set "com.yourdomain" in this file then the parameter will be set to default value of com.urdomain1
#	Note2:    If you do not set "ScstGroupName"  in this file then the parameter will be set to default value of lxc1
#	Note3:    If you do not set "AsmRedundancy"  in this file then the parameter will be set to default value of external
#	Note4:    If you do not set "Sysd1SizeGb"    in this file then the parameter will be set to default value of 1Gb
#	Note5:    If you do not set "Data1SizeGb"    in this file then the parameter will be set to default value of 1Gb 
#	Note6:    If you do not set "Reco1SizeGb"    in this file then the parameter will be set to default value of 1Gb 
#	Note8:    If you do not set "LogicalBlkSiz"  in this file then the parameter will be set to default value of 512 bytes
#
#	User:     Run this program as root if on RedHat/CentOS/Oracle Linux or similar; Run this program as the install admin user (user with 'sudo' privilege) if on Ubuntu or similar.
#	Usage:    create-scst-multipath.sh Owner Group Mode ContainerName 
#	Example:  create-scst-oracle.sh grid asmadmin 0660 lxc_luns
#
#	Note9:    If you do not set "Owner"  	     in this file then the parameter will be set to default value of grid
#	Note10:   If you do not set "Group"          in this file then the parameter will be set to default value of asmadmin
#	Note10:   If you do not set "Mode"           in this file then the parameter will be set to default value of 0660
#	Note11:   If you do not set "ContainerName"  in this file then the parameter will be set to default value of lxc_luns
#
#	4.	You can create the LUNs with 4K logical sector size if desired. The default is 512-byte logical sector size.
#		For the sysd1 sector size for Oracle, 512-byte is the required logical sector size.
#		For the data1 and reco1 the sector size can be 4096-byte (4K) optionally but be aware there are known caveats
#		so be sure you understand these before selecting 4096-byte logical sector sizes.
#	5.	On Ubuntu you may get a mix of actual devices mixed with symlinks in /dev/mapper after reboot.  This is due to some unknown issue in Ubuntu but seems fixed in 17.04.
#		You can get them all to be symlinks by stopping and starting multipath-tools and flushing the multipaths.  You might have to do this more than once but 1 or 2 cycles is usually 
#		enough to get them all over to symlinks (see example below).
#	6.	Below is shown the variety of storage options that are created automatically for you by the create-scst-multipath.sh script which creates the
#		/etc/multipath.conf and the /etc/udev/rules.d/99-oracle/rules files which together create the storage options below.
#	7.	If you are using LXC Linux containers you will want to use the storage that is in the location:  /dev/lxc_luns
#		If you have LXC containers running, then you should edit your /etc/udev/rules.d/99-oracle.rules file after the scripts have run so that subdirectories will be created under /dev
#		of the form /dev/ContainerName so that these directories will hold only the SCST LUNs that you will present to that specific lxc container.
#		That way, your lxc.mount directive only need reference that directory location so that the container only sees the storage it uses and no other storage LUNs.
#
#	STORAGE OPTIONS WHICH THESE SCRIPTS CREATE FOR YOU AUTOMATICALLY ARE SHOWN BELOW
#	ALL THESE OPTIONS POINT TO THE SAME STORAGE THEY ARE JUST DIFFERENT LOCATIONS OF THE SAME 3 LUNS
#
#	ubuntu@zesty-udev:~/Downloads/orabuntu-lxc-master/orabuntu/archives/scst-files$ ls -l /dev/lxc_luns/
#	total 0
#	brw-rw---- 1 grid asmadmin 253, 3 Sep  6 07:44 asm_data1_00
#	brw-rw---- 1 grid asmadmin 253, 4 Sep  6 07:44 asm_reco1_00
#	brw-rw---- 1 grid asmadmin 253, 2 Sep  6 07:44 asm_sysd1_00
#	ubuntu@zesty-udev:~/Downloads/orabuntu-lxc-master/orabuntu/archives/scst-files$ ls -l /dev/asm/
#	total 0
#	lrwxrwxrwx 1 root root 7 Sep  6 07:44 asm_data1_00 -> ../dm-3
#	lrwxrwxrwx 1 root root 7 Sep  6 07:44 asm_reco1_00 -> ../dm-4
#	lrwxrwxrwx 1 root root 7 Sep  6 07:44 asm_sysd1_00 -> ../dm-2
#	ubuntu@zesty-udev:~/Downloads/orabuntu-lxc-master/orabuntu/archives/scst-files$ ls -l /dev/mapper
#	total 0
#	lrwxrwxrwx 1 root root       7 Sep  6 07:44 asm_data1_00 -> ../dm-3
#	lrwxrwxrwx 1 root root       7 Sep  6 07:44 asm_reco1_00 -> ../dm-4
#	lrwxrwxrwx 1 root root       7 Sep  6 07:44 asm_sysd1_00 -> ../dm-2
#	crw------- 1 root root 10, 236 Sep  5 22:50 control
#	lrwxrwxrwx 1 root root       7 Sep  5 22:50 ubuntu--vg-root -> ../dm-0
#	lrwxrwxrwx 1 root root       7 Sep  5 22:50 ubuntu--vg-swap_1 -> ../dm-1
#	ubuntu@zesty-udev:~/Downloads/orabuntu-lxc-master/orabuntu/archives/scst-files$ ls -l /dev/dm*
#	brw-rw---- 1 root disk     253, 0 Sep  5 22:50 /dev/dm-0
#	brw-rw---- 1 root disk     253, 1 Sep  5 22:50 /dev/dm-1
#	brw-rw---- 1 grid asmadmin 253, 2 Sep  6 07:44 /dev/dm-2
#	brw-rw---- 1 grid asmadmin 253, 3 Sep  6 07:44 /dev/dm-3
#	brw-rw---- 1 grid asmadmin 253, 4 Sep  6 07:44 /dev/dm-4
#	ubuntu@zesty-udev:~/Downloads/orabuntu-lxc-master/orabuntu/archives/scst-files$ 

