ls -l /var/lib/lxc/lxcora01/config
ls -l /var/lib/lxc/lxcora01/rootfs/etc/ssh/sshd_config
ls -l /var/lib/lxc/lxcora01/rootfs/etc/sysconfig/network-scripts/ifcfg-eth0
ls -l /var/lib/lxc/lxcora01/rootfs/etc/sysctl.conf
ls -l /var/lib/lxc/lxcora01/rootfs/etc/dhcp/dhclient.conf
ls -l /var/lib/lxc/lxcora01/rootfs/home/grid/.bashrc
ls -l /var/lib/lxc/lxcora01/rootfs/home/oracle/.bashrc
ls -l /var/lib/lxc/lxcora01/rootfs/root/.bashrc
ls -l /var/lib/lxc/lxcora01/rootfs/etc/rc.d/rc.local
ls -l /var/lib/lxc/lxcora01/rootfs/etc/sysconfig/ntpd
ls -l /var/lib/lxc/lxcora01/rootfs/etc/fstab
ls -l /var/lib/lxc/lxcora01/rootfs/etc/security/limits.conf
ls -l /var/lib/lxc/lxcora01/rootfs/root/packages.sh
ls -l /var/lib/lxc/lxcora01/rootfs/root/create_directories.sh
ls -l /var/lib/lxc/lxcora01/rootfs/root/create_users.sh
ls -l /var/lib/lxc/lxcora01/rootfs/root/lxc-services.sh
ls -l /var/lib/lxc/lxcora01/rootfs/root/hugepages_setting.sh
ls -l /var/lib/lxc/lxcora01/rootfs/etc/nsswitch.conf
ls -l /var/lib/lxc/lxcora01/rootfs/etc/ntp.conf
ls -l /var/lib/lxc/lxcora01/rootfs/etc/selinux/config
ls -l /var/lib/lxc/lxcora01/rootfs/etc/sysconfig/network
ls -l /var/lib/lxc/lxcora01/rootfs/etc/selinux/config
ls -l /var/lib/lxc/lxcora01/rootfs/home/grid/grid/rpm/cvuqdisk-1.0.9-1.rpm
