sudo apt-get purge -y synaptic
sudo apt-get purge -y cpu-checker
sudo apt-get purge -y lxc
sudo apt-get purge -y uml-utilities
sudo apt-get purge -y openvswitch-switch
sudo apt-get purge -y openvswitch-common
sudo apt-get purge -y openvswitch-controller
sudo apt-get purge -y bind9
sudo apt-get purge -y bind9utils
sudo apt-get purge -y isc-dhcp-server
sudo apt-get purge -y apparmor-utils
sudo apt-get purge -y openssh-server
sudo apt-get purge -y uuid
sudo apt-get purge -y qemu-kvm
sudo apt-get purge -y libvirt-bin
sudo apt-get purge -y virt-manager
sudo apt-get purge -y rpm
sudo apt-get purge -y yum
sudo apt-get purge -y hugepages
sudo apt-get purge -y nfs-kernel-server
sudo apt-get purge -y nfs-common portmap
sudo apt-get purge -y multipath-tools
sudo apt-get purge -y open-iscsi 
sudo apt-get purge -y multipath-tools 
sudo apt-get purge -y ntp
sudo apt-get purge -y iotop
