ls -l /etc/multipath.conf
ls -l /etc/iscsi/initiatorname.iscsi
ls -l /etc/dhcp/dhcpd.conf
ls -l /etc/dhcp/dhclient.conf
ls -l /etc/bind/rndc.key
ls -l /etc/default/isc-dhcp-server
ls -l /etc/bind/named.conf.options
ls -l /etc/bind/named.conf.local
ls -l /etc/default/bind9
ls -l /var/lib/bind/rev.vmem.org
ls -l /var/lib/bind/fwd.vmem.org
ls -l /var/lib/bind/rev.mccc.org
ls -l /var/lib/bind/fwd.mccc.org
ls -l /etc/NetworkManager/dnsmasq.d/local
ls -l /etc/apparmor.d/lxc/lxc-default
ls -l /etc/security/limits.conf
ls -l /etc/sysctl.conf
ls -l /etc/exports
ls -l /etc/network/openvswitch/crt_ovs_sw1.sh
ls -l /etc/network/openvswitch/crt_ovs_sw2.sh
ls -l /etc/network/openvswitch/crt_ovs_sw3.sh
ls -l /etc/network/openvswitch/crt_ovs_sw4.sh
ls -l /etc/network/openvswitch/crt_ovs_sw5.sh
ls -l /etc/network/openvswitch/crt_ovs_sw6.sh
ls -l /etc/network/openvswitch/crt_ovs_sw7.sh
ls -l /etc/network/openvswitch/crt_ovs_sw8.sh
ls -l /etc/network/openvswitch/crt_ovs_sw9.sh
ls -l /etc/network/openvswitch/crt_ovs_sx1.sh
ls -l /etc/network/openvswitch/del-bridges.sh
ls -l /etc/network/if-up.d/openvswitch-net
ls -l /etc/scripts/nslookups.sh
ls -l /etc/scripts/crt_links.sh
