                        echo "=============================================="
                        echo "DISTRO RELEASE     KERN      TYPE EDITION     "
                        echo "CentOS Linux 6.x   ELREPO-4  V,P  ALL         "
                        echo "CentOS Linux 7.x   ALL       V,P  ALL         "
                        echo "Fedora Linux 27	   ALL       V,P  ALL       "
                        echo "Oracle Linux 6.x   UEK4      V,P  ALL         "
                        echo "Oracle Linux 7.x   RHEL,UEK4 V,P  ALL         "
                        echo "RedHat Linux 7.x   ALL       V,P  ALL,AWS     "
                        echo "Ubuntu Linux 16.x  ALL       V,P  S,D,AWS     "
                        echo "Ubuntu Linux 17.x  ALL       V,P  S,D         "
                        echo "Pop_OS Linux 17.x  ALL       V,P  ALL         "
                        echo "                                              "
                        echo "Legend:                                       "
                        echo "                                              "
                        echo "  V=Virtual Host                              "
                        echo "  P=Physical Host                             "
                        echo "  S=Server Edition                            "
                        echo "  D=Desktop Edition                           "
                        echo "  ALL=All Editions                            "
                        echo "  AWS=Amazon Web Services                     "
                        echo "  REL=Release                                 "
                        echo "  KERN=Kernel Version                         "
                        echo "=============================================="

