#!/bin/bash
#
#    Copyright 2015-2021 Gilbert Standen
#    This file is part of Orabuntu-LXC.

#    Orabuntu-LXC is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    Orabuntu-LXC is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with Orabuntu-LXC.  If not, see <http://www.gnu.org/licenses/>.

#    v2.4 		GLS 20151224
#    v2.8 		GLS 20151231
#    v3.0 		GLS 20160710 Updates for Ubuntu 16.04
#    v4.0 		GLS 20161025 DNS DHCP services moved into an LXC container
#    v5.0 		GLS 20170909 Orabuntu-LXC Multi-Host
#    v6.0-AMIDE-beta	GLS 20180106 Orabuntu-LXC AmazonS3 Multi-Host Docker Enterprise Edition (AMIDE)
#    v7.0-ELENA-beta    GLS 20210428 Enterprise LXD Edition New AMIDE

#    Note that this software builds a containerized DNS DHCP solution (bind9 / isc-dhcp-server).
#    The nameserver should NOT be the name of an EXISTING nameserver but an arbitrary name because this software is CREATING a new LXC-containerized nameserver.
#    The domain names can be arbitrary fictional names or they can be a domain that you actually own and operate.
#    There are two domains and two networks because the "seed" LXC containers are on a separate network from the production LXC containers.
#    If the domain is an actual domain, you will need to change the subnet using the subnets feature of Orabuntu-LXC

cd /opt/olxc/home/orabuntu/Downloads/orabuntu-lxc-master/products/k8s/kubernetes-master/lxd-provisioning

NameServer=afns1
ContainerRuntime=containerd

echo ''
echo "=============================================="
echo "Run cont-centos8-create.sh script...          "
echo "=============================================="
echo ''

sleep 5

clear

./cont-centos8-create.sh $NameServer

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-create.sh script.      "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run host-oracle8.sh script...          "
echo "=============================================="
echo ''

./host-oracle8.sh 

sleep 5

clear

echo ''
echo "=============================================="
echo "Done: Run host-oracle8.sh script.             "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push.sh script...            "
echo "=============================================="
echo ''

./cont-centos8-push.sh 

sleep 5

clear

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-push.sh script.        "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push-crio.sh...              "
echo "=============================================="
echo ''

./cont-centos8-push-crio.sh

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-push-crio.sh           "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push-containerd.sh ...       "
echo "=============================================="
echo ''

./cont-centos8-push-containerd.sh

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-push-containerd.sh     "
echo "=============================================="
echo ''

sleep 5

clear


echo ''
echo "=============================================="
echo "Run cont-centos8-exec-maestro.sh script...    "
echo "=============================================="
echo ''

sleep 5

clear

./cont-centos8-exec-maestro.sh $ContainerRuntime

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-exec-maestro.sh script "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-exec-violin1.sh script...    "
echo "=============================================="
echo ''

./cont-centos8-exec-violin1.sh $ContainerRuntime

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-exec-violin1.sh script "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-exec-violin2.sh script...    "
echo "=============================================="
echo ''

./cont-centos8-exec-violin2.sh $ContainerRuntime

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-exec-violin2.sh script "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push-ingress-nginx-examples  "
echo "=============================================="
echo ''

./cont-centos8-push-ingress-nginx-examples.sh

echo ''
echo "=============================================="
echo "Done: cont-centos8-push-ingress-nginx-example "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push-configmap...            "
echo "=============================================="
echo ''

./cont-centos8-push-configmap.sh

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-push-configmap.        "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-push-ingress-nginx-yaml...   "
echo "=============================================="
echo ''

./cont-centos8-push-ingress-nginx-yaml.sh

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-push-ingress-nginx-yaml"
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo '#######################################'
echo '# Following run only on maestro nodes:#'
echo '#######################################'

sleep 5

clear

echo ''
echo "=============================================="
echo "Run cont-centos8-5...                         "
echo "=============================================="
echo ''

eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- /root/cont-centos8-5.sh $ContainerRuntime' | sg lxd"

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-5.                     "
echo "=============================================="
echo ''

sleep 5

clear

if [ $ContainerRuntime = 'containerd' ]
then
	echo ''
	echo "=============================================="
	echo "Run cont-centos8-6 ...                        "
	echo "=============================================="
	echo ''

	for Node in violin1 violin2 maestro
	do
		echo 'Convert to containerd...'
		echo ' '
		eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- kubectl cordon $Node' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- kubectl drain  $Node --delete-emptydir-data --ignore-daemonsets' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl stop kubelet' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl stop docker' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- dnf remove docker-ce docker-ce-cli -y' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl stop containerd' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- containerd config default > /etc/containerd/config.toml' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- /root/cont-centos8-6.sh $ContainerRuntime $Node' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl enable containerd' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl start  containerd' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec $Node -- systemctl start kubelet' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- kubectl uncordon $Node' | sg lxd"
		eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- kubectl get -A nodes -o wide' | sg lxd"
	done

	echo ''
	echo "=============================================="
	echo "Done: Run cont-centos8-6.                     "
	echo "=============================================="
	echo ''

	sleep 5

	clear

	echo ''
	echo "=============================================="
	echo "Wait for all kube-system Running  ...         "
	echo "=============================================="
	echo ''

	function GetCountKubeSystem {
		kubectl get -A pods -o wide | grep -c kube-system
	}
	CountKubeSystem=$(GetCountKubeSystem)

	function GetCountKubeSystemRunning {
		kubectl get -A pods -o wide | grep kube-system | grep -c Running
	}
	CountKubeSystemRunning=$(GetCountKubeSystemRunning)

	n=1
	while [ $CountKubeSystemRunning -lt $CountKubeSystem ] && [ $n -le 5 ]
	do
		eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- kubectl get -A pods -o wide' | sg lxd"
		CountKubeSystem=$(GetCountKubeSystem)
		CountKubeSystemRunning=$(GetCountKubeSystemRunning)
		n=$((n+1))	
		sleep 60
	done

	echo ''
	echo "=============================================="
	echo "Done: Wait for all kube-system Running  ...   "
	echo "=============================================="
	echo ''
fi

# metallb load balancer deployment

echo ''
echo "=============================================="
echo "Run cont-centos8-7...                         "
echo "=============================================="
echo ''

eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- /root/cont-centos8-7.sh' | sg lxd"

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-7.                     "
echo "=============================================="
echo ''

# ingress-nginx deployment

echo ''
echo "=============================================="
echo "Run cont-centos8-8...                         "
echo "=============================================="
echo ''

eval echo "'/var/lib/snapd/snap/bin/lxc exec maestro -- /root/cont-centos8-8.sh' | sg lxd"

echo ''
echo "=============================================="
echo "Done: Run cont-centos8-8.                     "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Done: Create K8S cluster.                     "
echo "=============================================="
echo ''

sleep 5

clear

echo ''
echo "=============================================="
echo "Remove lib/modules mount...                   "
echo "=============================================="
echo ''

./host-oracle8-modules-remove.sh

echo ''
echo "=============================================="
echo "Done: Remove lib/modules mount.               "
echo "=============================================="
echo ''

sleep 5

clear


